columns:
  Age: int
  Sex: category
  ChestPainType: category
  RestingBP: int
  Cholesterol: int
  FastingBS: int
  RestingECG: category
  MaxHR: int
  ExerciseAngina: category
  Oldpeak: float
  ST_Slope: category
  HeartDisease: int